package cn.lv.hgstudy.pojo;

// Generated 2017-1-3 19:38:48 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Chapter generated by hbm2java
 */
public class Chapter implements java.io.Serializable {

	private Integer chapterId;
	private String chapterTitle;
	private Integer chapterIndex;
	private Integer couId;
	private String chapterInfor;
	private List joints = new ArrayList();

	public Chapter() {
	}

	public Chapter(String chapterTitle, Integer chapterIndex, Integer couId,
			String chapterInfor, List joints) {
		this.chapterTitle = chapterTitle;
		this.chapterIndex = chapterIndex;
		this.couId = couId;
		this.chapterInfor = chapterInfor;
		this.joints = joints;
	}

	public Integer getChapterId() {
		return this.chapterId;
	}

	public void setChapterId(Integer chapterId) {
		this.chapterId = chapterId;
	}

	public String getChapterTitle() {
		return this.chapterTitle;
	}

	public void setChapterTitle(String chapterTitle) {
		this.chapterTitle = chapterTitle;
	}

	public Integer getChapterIndex() {
		return this.chapterIndex;
	}

	public void setChapterIndex(Integer chapterIndex) {
		this.chapterIndex = chapterIndex;
	}

	public Integer getCouId() {
		return this.couId;
	}

	public void setCouId(Integer couId) {
		this.couId = couId;
	}

	public String getChapterInfor() {
		return this.chapterInfor;
	}

	public void setChapterInfor(String chapterInfor) {
		this.chapterInfor = chapterInfor;
	}

	public List getJoints() {
		return this.joints;
	}

	public void setJoints(List joints) {
		this.joints = joints;
	}

}
