package cn.lv.hgstudy.pojo;

// Generated 2017-3-19 22:02:52 by Hibernate Tools 3.4.0.CR1

/**
 * Playhistory generated by hbm2java
 */
public class StuAttention implements java.io.Serializable {

	private Integer attid;
	private Integer userid;
	private Integer couid;

	public StuAttention() {
	}
	public StuAttention(Integer couid) {
		this.couid = couid;
	}
	
	public StuAttention(Integer userid, Integer couid) {
		this.userid = userid;
		this.couid = couid;
	}
	public Integer getAttid() {
		return attid;
	}
	public void setAttid(Integer attid) {
		this.attid = attid;
	}
	public Integer getUserid() {
		return userid;
	}
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
	public Integer getCouid() {
		return couid;
	}
	public void setCouid(Integer couid) {
		this.couid = couid;
	}

	
}
