package cn.lv.hgstudy.pojo;

// Generated 2017-1-3 19:38:48 by Hibernate Tools 3.4.0.CR1

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private String teaId;
	private String teaName;
	private String teaTil;
	private String teaSchool;
	private Integer teaAge;
	private String teaPassword;
	private String teaSex;
	private String teaEduca;
	private String teaImage;
	private String emailAdress;
	
	public Teacher() {
	}

	public Teacher(String teaId) {
		this.teaId = teaId;
	}

	public Teacher(String teaId, String teaName, String teaTil,
			String teaSchool, Integer teaAge, String teaPassword,
			String teaSex, String teaEduca, String teaimage) {
		this.teaId = teaId;
		this.teaName = teaName;
		this.teaTil = teaTil;
		this.teaSchool = teaSchool;
		this.teaAge = teaAge;
		this.teaPassword = teaPassword;
		this.teaSex = teaSex;
		this.teaEduca = teaEduca;
		this.teaImage = teaimage;
	}

	public String getTeaId() {
		return this.teaId;
	}

	public void setTeaId(String teaId) {
		this.teaId = teaId;
	}

	public String getTeaName() {
		return this.teaName;
	}

	public void setTeaName(String teaName) {
		this.teaName = teaName;
	}

	public String getTeaTil() {
		return this.teaTil;
	}

	public void setTeaTil(String teaTil) {
		this.teaTil = teaTil;
	}

	public String getTeaSchool() {
		return this.teaSchool;
	}

	public void setTeaSchool(String teaSchool) {
		this.teaSchool = teaSchool;
	}

	public Integer getTeaAge() {
		return this.teaAge;
	}

	public void setTeaAge(Integer teaAge) {
		this.teaAge = teaAge;
	}

	public String getTeaPassword() {
		return this.teaPassword;
	}

	public void setTeaPassword(String teaPassword) {
		this.teaPassword = teaPassword;
	}

	public String getTeaSex() {
		return this.teaSex;
	}

	public void setTeaSex(String teaSex) {
		this.teaSex = teaSex;
	}

	public String getTeaEduca() {
		return this.teaEduca;
	}

	public void setTeaEduca(String teaEduca) {
		this.teaEduca = teaEduca;
	}

	public String getTeaImage() {
		return teaImage;
	}

	public void setTeaImage(String teaImage) {
		this.teaImage = teaImage;
	}

	public String getEmailAdress() {
		return emailAdress;
	}

	public void setEmailAdress(String emailAdress) {
		this.emailAdress = emailAdress;
	}
	
}
